{{ if .Values.deployments.trainingOperator.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: training-operator
  namespace: {{ .Values.argoCD.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "50"
    argocd.argoproj.io/manifest-generate-paths: .
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: kubeflow
  project: {{ .Values.projectName }}
  source:
    path: charts/13_training-operator
    repoURL: {{ .Values.sourceRepository }}
    targetRevision: {{ .Values.ref }}
    helm:
      releaseName: training-operator
      valueFiles:
        - values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
        - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: "5s"
        factor: 2
        maxDuration: "3m"
{{ end }}