apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-chart
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: kubeflow-project
  source:
    repoURL: https://github.com/prasadzende/kubeflow.git
    targetRevision: argo
    path: charts/1_istio
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  # Sync policy to automatically sync the application
  # and prune resources that are no longer tracked
  # and self heal resources that are out of sync  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
        - CreateNamespace=true