{{ if .Values.deployments.istio.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-chart
  namespace: {{ .Values.argoCD.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "10"
    argocd.argoproj.io/manifest-generate-paths: .
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.projectName }}
  source:
    repoURL: {{ .Values.sourceRepository }}
    targetRevision: {{ .Values.ref }}
    path: charts/1_istio
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  # Sync policy to automatically sync the application
  # and prune resources that are no longer tracked
  # and self heal resources that are out of sync  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
        - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: "5s"
        factor: 2
        maxDuration: "3m"
{{ end }}