sourceRepository: https://github.com/prasadzende/kubeflow.git
ref: "argo"
projectName: "kubeflow-project"

argoCD:
  namespace: "argocd"

deployments:

  istio:
    enabled: true
    helmValues: {}

  oauthProxy:
    enabled: true
  
  knative:
    enabled: true
  
  auth:
    enabled: true

  pipelines:
    enabled: true

  kserve:
    enabled: true
  
  centralDashboard:
    enabled: true

  admission-webhook:
    enabled: true